apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/go.png
name: bdd-ghfjxy-import-1584049087
version: 0.1.0-SNAPSHOT
